ignore:
  - "**/*.lock"
  - "**/*.toml"
  - "**/*.md"
  - "utils"
  - "**/tests"
  - "LICENSE"
  - ".github"
  - ".gitignore"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
