ignore:
  - "utils"
  - "tests"
  - "ARCHITECTURE.md"
  - "Cargo.lock"
  - "Cargo.toml"
  - "CHANGELOG.md"
  - "LICENSE"
  - "README.md"
  - ".github"
  - ".gitignore"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
