name: Feature request
description: Suggest an idea for this project
labels: ["t: feature"]

body:
  - type: markdown
    attributes:
      value: |
        Please take the time to fill out all relevant the fields below.

  - type: textarea
    id: feature
    attributes:
      label: A detailed description of the feature you would like to see added.
      description: |
        Explain how that feature would look like and how it should behave.
      placeholder: |
        I would love to see a configuration option to configure the color temperature of the terminal output.
        For instance, this could be done by adding a new configuration field to the `pueue.yml`.

        It would be enough for me to have a simple toggle between a `light` and `dark` mode.
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: Explain your usecase of the requested feature
      description: |
        I need to know what a feature is going to be used for, before I can decide if and how it's going to be implemented.

        The more information you provide, the better I understand your problem ;).
      placeholder: |
        I'm using a light terminal colorscheme and reading Pueue's output can be really hard from time to time.

        It would be awesome, if there was an option to have darker colors, so I'ts easier to read the output.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: |
        If your problem can be solved in multiple ways, I would like to hear the possible alternatives you've considered.

        Some problems really don't have any feasible alternatives, in that case don't bother answering this question :)
      placeholder: |
        I could add a wrapper around `pueue` that takes any output and rewrites the ANSI escape codes.
        However, this is very cumbersome and not user-friendly.

        This is why I think this should be in the upstream project.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: |
        Anything else you want to add such as sketches, screenshots, etc.
    validations:
      required: false
