[package]
name = "pueue-lib"
version = "0.21.2"
description = "The shared library to work with the Pueue client and daemon."
keywords = ["pueue"]
readme = "README.md"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
byteorder = "1.4"
chrono = { version = "0.4", features = ["serde"] }
dirs = "4.0"
rand = "0.8"
rcgen = "0.10"
rev_buf_reader = "0.3"
rustls = { version = "0.20", default-features = false }
rustls-pemfile = "1.0"
serde_cbor = "0.11"
serde_yaml = "0.9"
shellexpand = "3.0"
thiserror = "1.0"
tokio-rustls = { version = "0.23", default-features = false }

command-group = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_derive = { workspace = true }
snap = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "io-util"] }

[dev-dependencies]
anyhow = "1"
better-panic = "0.3"
pretty_assertions = "1"
portpicker = "0.1"
tempdir = "0.3"
tokio = { version = "1", features = ["time"] }

# --- Platform specific dependencies ---
# Windows
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = [
  "tlhelp32",
  "handleapi",
  "processthreadsapi",
  "minwindef",
  "impl-default",
] }

# Unix
[target.'cfg(unix)'.dependencies]
whoami = "1"

# Linux only
[target.'cfg(target_os = "linux")'.dependencies]
procfs = { version = "0.14.2", default-features = false }

# Apple only
[target.'cfg(target_vendor = "apple")'.dependencies]
libproc = "0.12.0"

[target.'cfg(target_vendor = "apple")'.dev-dependencies]
# Fork that fixes a version conflict, see heim-rs/darwin-libproc#3
# only used as a test dependency.
darwin-libproc = { git = "https://github.com/Nukesor/darwin-libproc.git", branch = "master" }
